### PR TITLE
Add plot!(f::Function) method

### PR DESCRIPTION
**Pull request by joshday**
I think it was this easy.  Tested with gadfly(), pyplot(), plotly().  Thanks for the pointer.

### CODE REVIEW

**Comment by pkofod** [comment]
Does it work with a vector of functions? At least the way it is currently, I would expect it to accept a vector of function, as the method is defined for `FuncOrFuncs`.

**Comment by tbreloff** [comment]
Yes it should be this easy :+1:

**Comment by pkofod** [comment]
Great stuff. After you mentioned it in the issue, I can really see great uses for it @joshday

**Comment by tbreloff** [comment]
Here's a fun little demo of the stuff that was just added.  How cool to be able to write `plot!(sin)`!

tmp

**Comment by KristofferC** [comment]
Nice

**Comment by pkofod** [comment]
I know all of the issues are plastered with praise for @tbreloff , but once again: I think you've really started _the_ package to point to for people who want to plot in Julia. Of course a lot of praise should go to the pyplot, gadfly, plotly, etc developers, but Plots.jl really ties it all together really well!

**Comment by tbreloff** [comment]
Thanks @pkofod ... I never get sick of compliments. :+1: 

At some point it would be cool to get the seal of approval from the core Julia developers and get official endorsement (maybe [here](http://julialang.org/downloads/plotting.html)?)... not sure the politics surrounding something like that...

**Comment by joshday** [comment]
@pkofod yes, it works with a vector of functions as well.  Yep, @tbreloff, you got a good thing going here.

**Pull request merged**
