### PR TITLE
fix ticks for pgfplots

### PR DESCRIPTION
**Pull request by KristofferC**
Not sure how the last one worked.. @pkofod ?

image

I also want to highlight the important fact that I almost got a nice star with random data.

### CODE REVIEW

**Comment by pkofod** [comment]
PR to `master` :scream:

**Comment by KristofferC** [comment]
OMG! I changed that but something was messed up and then I forgot to change it again...

**Comment by KristofferC** [comment]
No one commented on my star :(

**Comment by pkofod** [comment]
It is pretty!

**Pull request closed without merging**
