### PR TITLE
added writemime methods for plotly_blink

### PR DESCRIPTION
**Pull request by spencerlyon2**
This should not be merged until after JuliaIO/ImageMagick.jl#22

### CODE REVIEW

**Comment by tbreloff** [comment]
Awesome thanks!

**Comment by spencerlyon2** [comment]
Just added a commit that gets the PlotlyJS+Blink display working here

**Comment by spencerlyon2** [comment]
FYI, most of the explicit `Dict{Symbol,Any}` type declaring is not necessary, but `PlotlyJS.GenericTrace` and `PlotlyJS.Layout` both need an `Associative{Symbol,Any}` so I added the types everywhere just to be safe.

The lines that needed to be changed were in the call to `GenericTrace` in `_add_series` and the call to `relayout!` in `_update_plot`.

**Comment by tbreloff** [comment]
Any chance you can rebase on top of the `dev` branch?  If it's too much of a pain I can merge and try to deal with the mess.

**Comment by spencerlyon2** [comment]
done!

**Comment by tbreloff** [comment]
Sorry... can you re-open and merge into the dev branch (not master)?  You automatically picked up changes from another PR.

**Pull request closed without merging**
