### PR TITLE
arcdiagram

### PR DESCRIPTION
**Pull request by diegozea**
Hi @tbreloff !

This is the first attempt of **arc diagram** for **Plots.jl** :smiley: 
I hope you'll like it.  

arc

I let you the final tweaks. In particular, It would be great to show the color scale.
Also It would be great to have custom edges labels, as discussed in https://github.com/tbreloff/Plots.jl/issues/147

Best

### CODE REVIEW

**Comment by tbreloff** [comment]
Very cool! I'll merge when I'm at my computer. Thanks for the contribution.

**Comment by diegozea** [comment]
You're welcome! :)

**Comment by pkofod** [comment]
Looks awesome; art or practical use? :) (never seen such a plot before)

**Comment by diegozea** [comment]
@pkofod 

I use them to visualize information shared (MI) between columns of an MSA. My nodes (residues) are ordered, so I can easily see close and long range relations with them ;)

**References**

_Wattenberg, Martin. "Arc diagrams: Visualizing structure in strings." Information Visualization, 2002. INFOVIS 2002. IEEE Symposium on. IEEE, 2002._

**Pull request merged**
