### PR TITLE
add support for legend and label in pgfplots

### PR DESCRIPTION
**Pull request by KristofferC**
also adds some extra kwargs for legend positions

image

And one using a new kwarg for pyplot for example `:bottomright`

image

cc @pkofod

### CODE REVIEW

**Comment by KristofferC** [comment]
Should I throw an error is someone enters a legend kwarg that is not supported by pgfplots, ex `:top`?

**Comment by pkofod** [comment]
No, just allow for it, and place it in supported args. That's what I did for `stepmid` for example. thanks for adding this by the way.

**Comment by KristofferC** [comment]
>  place it in supported args

what do you mean by this? Anything I should change in the PR?

**Comment by tbreloff** [comment]
Merged thanks. Supported args isn't the right place for this (that would check that legends are supported, not `:top`)... you could add a warning and use a default value if you want.

**Comment by pkofod** [comment]
Sorry! I misread, I thought it said "enters a legend kwarg that is not supported by Plots", and I thought Kristoffer meant a kwarg that wasn't supported (currently) by other backends. My bad :)

**Pull request merged**
