### PR TITLE
Add abline! which creates a straight line according to the formula b+…

### PR DESCRIPTION
**Pull request by pkofod**
…a*x.

Implements #125 . The syntax matches with the name such that `abline!(a, b)` adds a straight line `b+a*x` based on only x-min and x-max.

Does it match with your usual style of coding @tbreloff or are there any changes you would like?

### CODE REVIEW

**Comment by tbreloff** [comment]
Thanks... There's a couple things...

- the method should take a "plt::Plot" as the first argument and pass that as the first argument in your inner call to 'plot!'.  Then you can add the convenience "abline!(args...;  kw...) = abline!(current(), args...; kw...)"
- min/max should look at all series, not just the first

Thanks for the PR

**Comment by pkofod** [comment]
Great suggestions. I just amended the changes, but I think you should be able to see the changes.

**Comment by pkofod** [comment]
Do you want `xmin` and `xmax` be exposed to the users?

**Comment by pkofod** [comment]
The failing CI seems to be comming from Gadfly markers, so it must be from the state of dev, not my PR. Added `Base.extrema(plt::Plot)` and changed code accordingly.

**Comment by tbreloff** [comment]
Yes I need to track down the markers behavior... Don't worry about that. 

This looks good... Can you post an example png here for reference? I'll merge today.

**Comment by pkofod** [comment]
I will do that. Do you want xmin, xmax and extrema exported?

**Comment by pkofod** [comment]
Code
```julia
using Plots

# The first series
x1 = [1; 4; 10; 30]
y1 = [0; 10; 3; 5]
# The second series
x2 = [2; 8; 15; 35]
y2 = [3; 5; 4; 8]

plot([x1 x2], [y1 y2])

abline!(0.2, 2)

#or
# plt = plot([x1 x2], [y1 y2])
# abline!(plt, 0.2, 2)

png("abline")
```
abline

**Comment by tbreloff** [comment]
No... there's no need to export extrema, as it's defined in base, and I don't think people should need xmin/xmax directly (and it can always be qualified). I just have a feeling I might want to change those names someday.

**Comment by pkofod** [comment]
Okay! I guess you could always deprecate them, but on the other hand I don't see a lot of requests for them either in other issues :) They'll remain unexported. Then I think we should be good to merge. Do you want me to squash the commits?

**Comment by tbreloff** [comment]
Merged... thanks for the contribution.  I'm happy to get more people involved to push this forward.

**Pull request merged**
